### ISSUE TITLE
How Can I Create My Own Train/Test Data?

### ISSUE THREAD

**Issue by talatccan** [onurgu/neural-turkish-morphological-disambiguator#5]
Hi, sorry im bothering a lot in last times. There are things im trying to understand.

I look into train and test files. How can i create my own train data like this one? Do i need to use something else for create it?

**Comment by onurgu** [comment]
The training and test files have a simple format.

Every line contains a SPACE separated token sequence of varying length.

The first token is the surface form (SF), the others are the candidate morphological analyses of that word. The first analysis (MA_1) must be the correct parse otherwise the order is not important.

SF MA_1 MA_2 ... MA_i ... MA_N

To create new datasets like these, one should run a morphological analyzer (like Oflazer's FST) on a tokenized version of the text, and manually select the correct parse among candidates output by the FST.
